### ISSUE TITLE
Working with Nightmare 2.6.1?

### ISSUE THREAD

**Issue by adityabansod** [zeekay/joseph#1]
I'm trying a simple script of this against the latest Nightmare (2.6.1) and not having any luck with even the Nightmare examples when this plugin is used:

``` javascript
var Nightmare = require('joseph')(require('nightmare'));
var nightmare = Nightmare({
    show: true,
    'ignore-certificate-errors': true,
    'web-security': false,
    'allow-displaying-insecure-content': true,
    openDevTools: {
        mode: 'detach'
    }
});

nightmare
  .goto('http://yahoo.com')
  .type('form[action*="/search"] [name=p]', 'github nightmare')
  .click('form[action*="/search"] [type=submit]')
  .wait('#main')
  .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

The code inside of `evaluate` is never executed on the page and the sequence hangs. 

If I remove the `require('jospeh')` and just used Nightmare on its own it works fine.

**Comment by zeekay** [comment]
I'll have a look at the latest version, something must have changed internally.

**Comment by adityabansod** [comment]
Thank you!

**Comment by zeekay** [comment]
Yeah, tests failing with 2.6. I'll try to take a look at it tonight.

**Comment by ambethia** [comment]
Any updates? I just ran into an issue where I need to do asynchronous evals in Nightmare. Thanks! I'll lend a hand if I can.

**Comment by zeekay** [comment]
I'll need to review their internal API and figure out what has changed. You can use an older version of nightmare in interim. I'm on Gitter if you want to plough through things with me.
—
Zach Kelling
$ curl monoid.io/say-hi | python
zk@monoid.io / (913) 777-9708

**Comment by jesstelford** [comment]
Some investigation shows the tests started failing in `nightmare@2.1.6`:

<details>

```
$ npm install --save-dev nightmare@2.1.6 && npm run test

joseph@0.2.9 /Users/jess.telford/dev/joseph
└── nightmare@2.1.6


> joseph@0.2.9 test /Users/jess.telford/dev/joseph
> cake test



  joseph
    ✓ should evaluate synchronous functions (95ms)
    1) should support node.js style callbacks
    ✓ should wait for promise to complete
    ✓ should handle promise rejection
    2) should pass in arguments correctly
    ✓ should consume generators
    ✓ should catch errors thrown in a generator
    - should handle asynchronicity correctly


  5 passing (476ms)
  1 pending
  2 failing

  1) joseph should support node.js style callbacks:
     Error: eep
      at <anonymous>:109:21

  2) joseph should pass in arguments correctly:
     Error: ohno
      at <anonymous>:108:31
      at evalSync (<anonymous>:89:15)
      at <anonymous>:98:16
      at <anonymous>:107:2
      at EventEmitter.electron.ipcRenderer.on (node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/init.js:44:29)
      at EventEmitter.ipcRenderer.emit (node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/ipc.js:17:38)
```

</details>

**Comment by jesstelford** [comment]
Some more details, it looks like performing the following change will get the code to evaluate. However, 2 of the tests still fail (to do with the error states):

<details>

``` diff
diff --git a/src/evaluate.coffee b/src/evaluate.coffee
index 042b372..80c7f22 100644
--- a/src/evaluate.coffee
+++ b/src/evaluate.coffee
@@ -12,7 +12,7 @@ module.exports = (fn, args...) ->

   js = "(#{script}(#{String fn}, #{JSON.stringify args}))"

-  @child.once 'javascript', (errstr, result) ->
+  @child.call 'javascript', js, (errstr, result) ->
     if errstr?
       errmsg    = JSON.parse errstr
       err       = new Error errmsg.message
@@ -22,5 +22,4 @@ module.exports = (fn, args...) ->
     else
       done null, JSON.parse result

-  @child.emit 'javascript', js
   @
```

</details>

Unfortunately I'm not able to investigate further (time constraints), but hopefully it's enough to help @zeekay?

**Comment by zeekay** [comment]
I published a new version which pins Nightmare at 2.0.8 (last working version apparently). I'll investigate making it work with later versions this week.

**Comment by zeekay** [comment]
Actually it was a dev dependency, I guess. I suppose I should make it an actual dependency and pin it to a specific version of nightmare as their API seems to be highly in flux.

**Comment by zeekay** [comment]
I think I have a pretty clear idea how to update this to support the latest version of nightmare so I'll do that soon enough.

**Comment by mateuszmazurek** [comment]
@zeekay any updates? :)
